
DEFAULT_ROM_FILE_EXTS = ['iso', 'zip', 'sfc', 'gba', 'gbc', 'gb', 'md', 'n64',
						 'nes', '32x', 'gg', 'sms', 'bin', 'exe']
PLATFORMS = [
	'3DO',
	'Amstrad CPC',
	'Arcade',
	'Atari 2600',
	'Atari 7800',
	'Atari 800/5200',
	'Atari 8bit computers',
	'Atari Jaguar',
	'Atari Lynx',
	'Atari ST/STE/TT/Falcon',
	'Bandai WonderSwan',
	'ChaiLove',
	'Commodore 128',
	'Commodore 16/Plus/4',
	'Commodore 64',
	'Commodore VIC-20'
	'J2ME',
	'Magnavox Odyssey²',
	'MS-DOS',
	'MSX/MSX2/MSX2+',
	'NEC PC Engine (SuperGrafx)',
	'NEC PC Engine (TurboGrafx-16)',
	'NEC PC Engine TurboGrafx-16',
	'NEC PC-98',
	'NEC PC-FX',
	'Nintendo 3DS',
	'Nintendo DS',
	'Nintendo Game Boy (Color)',
	'Nintendo Game Boy Advance',
	'Nintendo Game Boy Color',
	'Nintendo GameCube',
	'Nintendo N64',
	'Nintendo NES',
	'Nintendo SNES',
	'Nintendo Virtual Boy',
	'Nintendo Wii',
	'Nintendo Wii/Gamecube',
	'Sega Dreamcast',
	'Sega Game Gear',
	'Sega Genesis',
	'Sega Genesis/Mega Drive',
	'Sega Maste System/Gamegear',
	'Sega Master System',
	'Sega Saturn',
	'Sharp X68000',
	'Sinclair ZX Spectrum',
	'Sinclair ZX81',
	'SNK Neo Geo Pocket (Color)',
	'SNK Neo Geo Pocket',
	'Sony PlayStation 2',
	'Sony PlayStation 3',
	'Sony PlayStation Portable',
	'Sony PlayStation',
	'Uzebox',
	'Vectrex',
	'Windows',
	'Z-Machine'
]


IGNORE_TYPES = [
		"7-zip archive data",
		"Algol 68 source",
		"Applesoft BASIC program data",
		"color profile 2.0",
		"Crunch compressed texture",
		"DOS batch file",
		"DOS executable (block device driver)",
		"DOS/MBR boot sector",
		"executable",
		"FLAC audio bitstream data",
		"IFF data",
		"InnoSetup Log",
		"Intel ia64 COFF object file",
		"ISO Media",
		"ISO-8859 text ",
		"ISO-8859 text",
		"Java archive data (JAR)",
		"Java KeyStore",
		"Mach-O 64-bit x86_64 bundle",
		"Mach-O 64-bit x86_64 dynamically linked shared library",
		"Microsoft color profile 2.1",
		"MPEG sequence",
		"MS Windows 95 Internet shortcut text (URL=<http://www.rapapuru.com/>)",
		"MS Windows 95 Internet shortcut",
		"MS Windows icon resource - 11 icons",
		"MS Windows icon resource",
		"NekoVM bytecode",
		"Ogg data",
		"OpenPGP Public Key",
		"OpenType font data /run/media/mmcblk0p1/deck_sync/HG/GenderBender/renpy/common/fa5.otf",
		"OpenType font data",
		"Paint.NET image data",
		"PC bitmap ",
		"PC bitmap",
		"PDF document",
		"python 3.8 byte-compiled",
		"raw G3 (Group 3) FAX",
		"RIFF (big-endian) data",
		"RIFF (little-endian) data",
		"Spectrum .TAP data",
		"Standard MIDI data ",
		"Standard MIDI data",
		"Sun KCMS color profile 2.0",
		"SysEx File",
		"Targa image data",
		"TTComp archive data",
		"Unicode text",
		"Windows desktop.ini",
		'Adobe Photoshop Image',
		'Apple Desktop Services Store',
		'ASCII text',
		'Audio file with ID3 version ',
		'C source',
		'C source, ASCII text',
		'C++ source',
		'CSV text',
		'data',
		'DIY-Thermocam',
		'ELF 32-bit LSB shared object',
		'ELF 64-bit LSB shared object',
		'empty',
		'exported SGML document',
		'Generic INItialization configuration',
		'GIF image data',
		'GIMP XCF image data',
		'HTML document',
		'JPEG image data',
		'JSON data',
		'MPEG ADTS',
		'MS Windows 3.1 help',
		'MS Windows help file Content',
		'MS Windows shortcut',
		'Non-ISO extended-ASCII text',
		'Ogg data, Vorbis audio',
		'PC bitmap',
		'PDF document ',
		'PE32 executable (DLL)',
		'PE32+ executable (DLL)',
		'PEM certificate',
		'PEM RSA private key',
		'PNG image data',
		'POSIX shell script',
		'POSIX tar archive',
		'python 2.7 byte-compiled',
		'RAR archive data',
		'Ruby script',
		'SVG Scalable Vector Graphics image',
		'TrueType Font data,',
		'Web Open Font Format',
		'WebAssembly',
		'WebM',
		'Windows WIN.INI',
		'XML 1.0 document',
		'Zip archive data',
		'zlib compressed data',

		# Revisit?
		'Python script, ASCII text',
		'Python script text executable Python script',
		'Python script, Unicode text',

		# Is there a runner for mac binaries?
		"Mach-O 64-bit x86_64 executable",
		"Mach-O universal binary",
	]



IGNORE_BINARIES = set([
	"ffmpeg",
	"zsyncmake",
	"zsync",
	"unitycrashhandler64",
	"unitycrashhandler32",
	"python",
	"pythonw",
	"notification_helper",
	"dxwebsetup",
	"jjs",
	"qgen",
	"pack200",
	"javacpl",
	"java.exe",
	"unins000",
	"ue4prereqsetup_x64",
	"uninstaller",
	"config",
	"unpack200",
	"resetconfig",
	"claunchus",
	"servertool",
	"orbd",
	"nwjc",
	"policytool",
	"rmiregistry",
	"cwebp",
	"ueprereqsetup_x64",
	"tnameserv",
	"launcher",
	"subprocess",
	"ktab",
	"klist",
	"kinit",
	"jp2launcher",
	"jabswitch",
	"pysemver",
	"payload",
	"rmid",
	"java",
	"vcredist-x64",
	"vcredist-x86",
	"vcredist_x64",
	"vcredist_x86",
	"javaw",
	"javaws",
	"opensavefolder",
	])


LINUX_EXECUTABLES = [
	"ELF 32-bit LSB",
	"ELF 64-bit LSB",
]

WINDOWS_EXECUTABLES = [
	"PE32 executable",
	"PE32+ executable",
]